### ISSUE TITLE
websocket无法响应action,是什么问题呢？

### ISSUE THREAD

**Issue by qfgyd2004** [thinkjs/thinkjs#1234]
thinkjs  2.2版本
配置文件
```js
export default {
  on: true, //是否开启 WebSocket
  type: 'socket.io', //使用的 WebSocket 库类型，默认为 socket.io
  allow_origin: '*', //允许的 origin
  adp: undefined, // socket 存储的 adapter，socket.io 下使用
  path: '', //url path for websocket
  messages: {
    open: 'api/build/open', // WebSocket 建立连接时处理的 Action
    close: 'api/build/close', // WebSocket 关闭时处理的 Action
    update: 'api/build/update', // 
  }
};
```
通过http 可以访问open
socket无论如何无法响应open action

**Comment by lizheming** [comment]
Your websocket config seems correct, please give more info to detect your bug. Or you can consult [anychat](https://github.com/lizheming/anychat) project which is about websocket chatroom by ThinkJS 2. By the way, if you just started to develop your project, we recommend you upgrade to ThinkJS 3. The most of reason is ThinkJS 2 is too old and we have not provide support now.

**Comment by qfgyd2004** [comment]
![image](https://user-images.githubusercontent.com/4167554/44965308-6e310a00-af67-11e8-8b06-1f2b68b6ca2a.png)
build controller
前端使用  webpackDevServer 
添加了代理转发
`proxy: {
       '/api': {
         target: 'http://127.0.0.1:8360',
       },
    }
`
polling 方式返回400错误
websocket 方式 opcode -1

**Comment by lizheming** [comment]
It's your proxy problem, webpack-dev-server just proxy http request, but websocket is `ws://` protocol. You should read more about websocket protocol. Maybe [this link](https://stackoverflow.com/questions/31654239/proxy-websockets-connection-within-webpack-dev-server) will help you. I'm closing this issue because it is an outside config bug that we have no control over. You also can comment if you have any doubt.

**Comment by qfgyd2004** [comment]
感谢！
