### ISSUE TITLE
insertId 返回问题

### ISSUE THREAD

**Issue by zhanyangqi** [thinkjs/thinkjs#1244]
## DESC

postgresql 使用 model().add() 新增数据返回 uuid 的主键成功，但并不能完整返回 uuid

### ENV

    "ali-oss": "^6.0.1",
    "think-cache": "^1.0.0",
    "think-cache-file": "^1.0.8",
    "think-fetch": "^1.1.0",
    "think-logger3": "^1.0.0",
    "think-model": "^1.0.0",
    "think-model-mysql": "^1.0.0",
    "think-model-postgresql": "^1.1.1",
    "think-mongoose": "^1.0.3",
    "think-session": "^1.0.0",
    "think-session-file": "^1.0.5",
    "think-view": "^1.0.0",
    "think-view-nunjucks": "^1.0.1",
    "thinkjs": "^3.0.0"

**Comment by lizheming** [comment]
https://github.com/thinkjs/think-model-postgresql/blob/master/lib/query.js#L28-L33 
postgresql insertId will parsed as number, if your primary key is not number, it actually get wrong key.

**Comment by lizheming** [comment]
https://stackoverflow.com/questions/2944297/postgresql-function-for-last-inserted-id 
We can use `RETURNING id;` for postgresql get insertid. @welefen

**Comment by welefen** [comment]
please set pk property in model, like:

```js
get pk() {
   return 'uuid';
}
```

**Comment by lizheming** [comment]
As [source code](https://github.com/thinkjs/think-model-postgresql/blob/master/lib/parser.js#L116-L120) said, you should set primary key using like `get pk() { return 'uuid'; }` so we can append `RETURNING uuid;` to your insert sql. 

After that, it still have something wrong in old version because of `parseInt`. So we [add number string check before parse](https://github.com/thinkjs/think-model-postgresql/pull/1/files#diff-32a8cfb1af74860f3233cd24dcd57fadR36) to avoid it, please upgrade to `think-model-postgresql@1.1.2`.
