### ISSUE TITLE
nginx部署项目失败

### ISSUE THREAD

**Issue by DengRiGuang** [thinkjs/thinkjs#1275]
### ENV

OS Platform:
centos 7.5
Node.js Version:
8.12.0
ThinkJS Version:
3.0
### code

```js
nginx.conf
server {
    listen 80;
    server_name 120.78.139.148;
    root /data/www/word-node/www;
    set $node_port 8360;

    index index.js index.html index.htm;
    if ( -f $request_filename/index.html ){
        rewrite (.*) $1/index.html break;
    }
    if ( !-f $request_filename ){
        rewrite (.*) /index.js;
    }
    location = /index.js {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://127.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location ~ /static/ {
        etag         on;
        expires      max;
    }
}
```

### error message

```
502 Bad Gateway
```

### more description
pm2启动 errored
// your detail description

**Comment by welefen** [comment]
pm2启动 errored，说明有报错啊

**Comment by sailengsi** [comment]
查看下pm2错误日志。

**Comment by sailengsi** [comment]
这不是说你没有找到thinkjs么？依赖安装齐全了么？




    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年10月31日 09:26，riguang 写道： @sailengsi 报的是这个
1|word-nod |     at Object.Module._extensions..js (module.js:664:10)
1|word-nod |     at Module.load (module.js:566:32)
1|word-nod |     at tryModuleLoad (module.js:506:12)
1|word-nod |     at Function.Module._load (module.js:498:3)
1|word-nod | Error: Cannot find module 'thinkjs'
1|word-nod |     at Function.Module._resolveFilename (module.js:548:15)
1|word-nod |     at Function.Module._load (module.js:475:25)
1|word-nod |     at Module.require (module.js:597:17)
1|word-nod |     at require (internal/module.js:11:18)
1|word-nod |     at Object. (/data/www/word-node/production.js:2:21)
1|word-nod |     at Module._compile (module.js:653:30)
1|word-nod |     at Object.Module._extensions..js (module.js:664:10)
1|word-nod |     at Module.load (module.js:566:32)
1|word-nod |     at tryModuleLoad (module.js:506:12)
1|word-nod |     at Function.Module._load (module.js:498:3)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1275:  @sailengsi 报的是这个\r\n1|word-nod |     at Object.Module._extensions..js (module.js:664:10)\r\n1|word-nod |     at Module.load (module.js:566:32)\r\n1|word-nod |     at tryModuleLoad (module.js:506:12)\r\n1|word-nod |     at Function.Module._load (module.js:498:3)\r\n1|word-nod | Error: Cannot find module 'thinkjs'\r\n1|word-nod |     at Function.Module._resolveFilename (module.js:548:15)\r\n1|word-nod |     at Function.Module._load (module.js:475:25)\r\n1|word-nod |     at Module.require (module.js:597:17)\r\n1|word-nod |     at require (internal/module.js:11:18)\r\n1|word-nod |     at Object.\u003canonymous\u003e (/data/www/word-node/production.js:2:21)\r\n1|word-nod |     at Module._compile (module.js:653:30)\r\n1|word-nod |     at Object.Module._extensions..js (module.js:664:10)\r\n1|word-nod |     at Module.load (module.js:566:32)\r\n1|word-nod |     at tryModuleLoad (module.js:506:12)\r\n1|word-nod |     at Function.Module._load (module.js:498:3)"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552",
"url": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] nginx部署项目失败 (#1275)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402963070\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sailengsi** [comment]
这不是说你没有找到thinkjs么？依赖安装齐全了么？



    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年10月31日 09:26，riguang 写道： @sailengsi 报的是这个
1|word-nod |     at Object.Module._extensions..js (module.js:664:10)
1|word-nod |     at Module.load (module.js:566:32)
1|word-nod |     at tryModuleLoad (module.js:506:12)
1|word-nod |     at Function.Module._load (module.js:498:3)
1|word-nod | Error: Cannot find module 'thinkjs'
1|word-nod |     at Function.Module._resolveFilename (module.js:548:15)
1|word-nod |     at Function.Module._load (module.js:475:25)
1|word-nod |     at Module.require (module.js:597:17)
1|word-nod |     at require (internal/module.js:11:18)
1|word-nod |     at Object. (/data/www/word-node/production.js:2:21)
1|word-nod |     at Module._compile (module.js:653:30)
1|word-nod |     at Object.Module._extensions..js (module.js:664:10)
1|word-nod |     at Module.load (module.js:566:32)
1|word-nod |     at tryModuleLoad (module.js:506:12)
1|word-nod |     at Function.Module._load (module.js:498:3)

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1275:  @sailengsi 报的是这个\r\n1|word-nod |     at Object.Module._extensions..js (module.js:664:10)\r\n1|word-nod |     at Module.load (module.js:566:32)\r\n1|word-nod |     at tryModuleLoad (module.js:506:12)\r\n1|word-nod |     at Function.Module._load (module.js:498:3)\r\n1|word-nod | Error: Cannot find module 'thinkjs'\r\n1|word-nod |     at Function.Module._resolveFilename (module.js:548:15)\r\n1|word-nod |     at Function.Module._load (module.js:475:25)\r\n1|word-nod |     at Module.require (module.js:597:17)\r\n1|word-nod |     at require (internal/module.js:11:18)\r\n1|word-nod |     at Object.\u003canonymous\u003e (/data/www/word-node/production.js:2:21)\r\n1|word-nod |     at Module._compile (module.js:653:30)\r\n1|word-nod |     at Object.Module._extensions..js (module.js:664:10)\r\n1|word-nod |     at Module.load (module.js:566:32)\r\n1|word-nod |     at tryModuleLoad (module.js:506:12)\r\n1|word-nod |     at Function.Module._load (module.js:498:3)"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552",
"url": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] nginx部署项目失败 (#1275)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434528552"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402963070\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by DengRiGuang** [comment]
服务器上也要装依赖的？

**Comment by sailengsi** [comment]
当然了，pm2只是后台运行而已，和正常的npm start需要的条件是一样的。



    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年10月31日 09:36，riguang 写道： 服务器上也要装依赖的？

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1275: 服务器上也要装依赖的？"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530298"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530298",
"url": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530298",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] nginx部署项目失败 (#1275)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530298"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402963070\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by DengRiGuang** [comment]
我直接npm install 装不上的

**Comment by sailengsi** [comment]
不可能的，那就是你服务器node环境有问题，你先把服务器node环境弄好，然后用npm start测试是否成功启动来测试，测试ok的话，再pm2。一步一步来！



    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年10月31日 09:39，riguang 写道： 我直接npm install 装不上的

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1275: 我直接npm install 装不上的"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530839"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530839",
"url": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530839",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] nginx部署项目失败 (#1275)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434530839"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402963070\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by DengRiGuang** [comment]
好了，npm install 错文件夹了，还有我想问一下，用了PM2，还用nginx有必要的嘛，没感觉出有什么加成啊

**Comment by sailengsi** [comment]
首先你要理解他们是干嘛的，pm2只是解决node项目后台运行，Nginx是web服务器，在node项目里，正常启动往往都是只能通过ip加端口号启动，而Nginx是实现可以用域名访问。请先理解一下他们的概念，谢谢！



    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年10月31日 09:46，riguang 写道： 好了，npm install 错文件夹了，还有我想问一下，用了PM2，还用nginx有必要的嘛，没感觉出有什么加成啊

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1275: 好了，npm install 错文件夹了，还有我想问一下，用了PM2，还用nginx有必要的嘛，没感觉出有什么加成啊"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986",
"url": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] nginx部署项目失败 (#1275)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402963070\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by sailengsi** [comment]
纠正一下，只能用ip加端口号访问，不是启动，手误，谢谢！



    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年10月31日 09:50，git 写道： 
        
            首先你要理解他们是干嘛的，pm2只是解决node项目后台运行，Nginx是web服务器，在node项目里，正常启动往往都是只能通过ip加端口号启动，而Nginx是实现可以用域名访问。请先理解一下他们的概念，谢谢！



    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


            在2018年10月31日 09:46，riguang 写道： 好了，npm install 错文件夹了，还有我想问一下，用了PM2，还用nginx有必要的嘛，没感觉出有什么加成啊

—You are receiving this because you were mentioned.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1275: 好了，npm install 错文件夹了，还有我想问一下，用了PM2，还用nginx有必要的嘛，没感觉出有什么加成啊"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986",
"url": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] nginx部署项目失败 (#1275)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1275\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1275#issuecomment-434531986"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 402963070\n}"
}
],
"themeColor": "26292E"
}
]

**Comment by DengRiGuang** [comment]
好的
