### ISSUE TITLE
PM2 启动成功，但通过配置好的域名无法访问

### ISSUE THREAD

**Issue by DengRiGuang** [thinkjs/thinkjs#1285]
### ENV

OS Platform:
window10
Node.js Version:
8.12.0
ThinkJS Version:
3.0.0
### code

```js
server {
    listen 80;
    server_name api.dengriguang.com;
    root /data/word-node;
    set $node_port 8360;

    index index.js index.html index.htm;
    if ( -f $request_filename/index.html ){
        rewrite (.*) $1/index.html break;
    }
    if ( !-f $request_filename ){
        rewrite (.*) /index.js;
    }
    location = /index.js {
        proxy_http_version 1.1;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header Host $http_host;
        proxy_set_header X-NginX-Proxy true;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
        proxy_pass http://120.0.0.1:$node_port$request_uri;
        proxy_redirect off;
    }

    location ~ /static/ {
        etag         on;
        expires      max;
    }
}
```

### error message

```
502 Bad Gateway
```

### more description

ping域名是可以ping通的

**Comment by lushijie** [comment]
你的 root 应该配置错了

**Comment by DengRiGuang** [comment]
目录是对的，data下有word-node

**Comment by sailengsi** [comment]
可以先尝试一下端口访问是否正常，结合pm2日志查看一下。




    
    
        
            
                
                    
                        
                    
                    
                        
                            git
                            
                            
                                
                                    邮箱：git@sailengsi.com
                                
                        
                    
                
            
        
    
Signature is customized by Netease Mail Master


在2018年11月13日 10:27，riguang 写道： 目录是对的，data下有word-node

—You are receiving this because you are subscribed to this thread.Reply to this email directly, view it on GitHub, or mute the thread.
{"api_version":"1.0","publisher":{"api_key":"05dde50f1d1a384dd78767c55493e4bb","name":"GitHub"},"entity":{"external_key":"github/thinkjs/thinkjs","title":"thinkjs/thinkjs","subtitle":"GitHub repository","main_image_url":"https://assets-cdn.github.com/images/email/message_cards/header.png","avatar_image_url":"https://assets-cdn.github.com/images/email/message_cards/avatar.png","action":{"name":"Open in GitHub","url":"https://github.com/thinkjs/thinkjs"}},"updates":{"snippets":[{"icon":"PERSON","message":"@DengRiGuang in #1285: 目录是对的，data下有word-node"}],"action":{"name":"View Issue","url":"https://github.com/thinkjs/thinkjs/issues/1285#issuecomment-438106241"}}}
[
{
"@context": "http://schema.org",
"@type": "EmailMessage",
"potentialAction": {
"@type": "ViewAction",
"target": "https://github.com/thinkjs/thinkjs/issues/1285#issuecomment-438106241",
"url": "https://github.com/thinkjs/thinkjs/issues/1285#issuecomment-438106241",
"name": "View Issue"
},
"description": "View this Issue on GitHub",
"publisher": {
"@type": "Organization",
"name": "GitHub",
"url": "https://github.com"
}
},
{
"@type": "MessageCard",
"@context": "http://schema.org/extensions",
"hideOriginalBody": "false",
"originator": "AF6C5A86-E920-430C-9C59-A73278B5EFEB",
"title": "Re: [thinkjs/thinkjs] PM2 启动成功，但通过配置好的域名无法访问 (#1285)",
"sections": [
{
"text": "",
"activityTitle": "**riguang**",
"activityImage": "https://assets-cdn.github.com/images/email/message_cards/avatar.png",
"activitySubtitle": "@DengRiGuang",
"facts": [

]
}
],
"potentialAction": [
{
"name": "Add a comment",
"@type": "ActionCard",
"inputs": [
{
"isMultiLine": true,
"@type": "TextInput",
"id": "IssueComment",
"isRequired": false
}
],
"actions": [
{
"name": "Comment",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueComment\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1285,\n\"IssueComment\": \"{{IssueComment.value}}\"\n}"
}
]
},
{
"name": "Close issue",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"IssueClose\",\n\"repositoryFullName\": \"thinkjs/thinkjs\",\n\"issueId\": 1285\n}"
},
{
"targets": [
{
"os": "default",
"uri": "https://github.com/thinkjs/thinkjs/issues/1285#issuecomment-438106241"
}
],
"@type": "OpenUri",
"name": "View on GitHub"
},
{
"name": "Unsubscribe",
"@type": "HttpPOST",
"target": "https://api.github.com",
"body": "{\n\"commandName\": \"MuteNotification\",\n\"threadId\": 409673187\n}"
}
],
"themeColor": "26292E"
}
]
