### ISSUE TITLE
docs broken

### ISSUE THREAD

**Issue by RWOverdijk** [thinkjs/thinkjs#789]
The docs are broken.

https://thinkjs.org/doc/index.html

**Comment by lizheming** [comment]
sorry, https://thinkjs.org/en/doc/2.2/index.html you can use this link temporary.  We publish 3.0 today, but english documentation has not ready. We'll fixed it immediately.

**Comment by lizheming** [comment]
I has fixed broken. But I don't recommend you watch documentation right now. Because the latest english doc is 2.2 version, and it's older than chinese doc which latest is version 3.0. Close this issue firstly and we will update version 3.0 english doc recently. If well done I'll notify you in this issue. Thank you very much!
